### ISSUE TITLE
RUSSLEY VRP still present in Euroscope Dataset

### ISSUE THREAD

**Issue by rb-vatnz** [vatnz-dev/new-zealand-dataset#43]
![image](https://github.com/vatnz-dev/new-zealand-dataset/assets/125234863/28ac984f-52a8-4f04-b0b6-4345c5996592)

RUSSLEY VRP is still present in Euroscope dataset although it is no longer in the ANR.

**Comment by dirtyformal** [comment]
Looks like the new VRPs weren't being copied across in the ESE/SCT2 conversion. 

RUSSLEY no longer present, and additional other new VRPs (RICCARTON RACECOURSE) are in place instead. Closing.
