### ISSUE TITLE
Rename Dataset to "VATNZ Domestic (NZZC)"

### ISSUE THREAD

**Issue by dirtyformal** [vatnz-dev/new-zealand-dataset#52]
As per discussion in the #controller-clients channel. Renaming the dataset aligns with the Combined Oceanic dataset.

**Comment by rb-vatnz** [comment]
@dirtyformal, just confirming renaming in this case means a change in the profile directory name? The ATISPlugin now contains a fixed pathname to the profile for the purposes of pulling the XML files so will need to change to match if that's the case.

**Comment by dirtyformal** [comment]
> @dirtyformal, just confirming renaming in this case means a change in the profile directory name? The ATISPlugin now contains a fixed pathname to the profile for the purposes of pulling the XML files so will need to change to match if that's the case.

Just in the name presented to the user on the Profile loading screen. The directory structure and name presented to the user in the profile selection window are unchanged.

Should be non-breaking for all other references to the dataset.

**Comment by rb-vatnz** [comment]
Ah cool - that profile name that shows in the loading screen is also important for ATISPlugin as well, but luckily the code I have already should match the new name still:
`if (!Profile.Name.Contains("NZZC")) return;`
